### ISSUE TITLE
DREAM random initialiser appears to be broken

### ISSUE THREAD

**Issue by acaruana2009** [bumps/bumps#71]
The following traceback occurs upon trying to use the `random` initialiser for DREAM (at least in the GUI, I have yet to check using the CLI):

Exception in thread Thread-6:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\programdata\anaconda3\lib\site-packages\bumps\gui\fit_thread.py", line 204, in run
    x, fx = driver.fit()
  File "c:\programdata\anaconda3\lib\site-packages\bumps\fitters.py", line 969, in fit
    x, fx = fitter.solve(monitors=self.monitors,
  File "c:\programdata\anaconda3\lib\site-packages\bumps\fitters.py", line 796, in solve
    self.state = sampler.sample(state=self.state, abort_test=abort_test)
  File "c:\programdata\anaconda3\lib\site-packages\bumps\dream\core.py", line 235, in sample
    _run_dream(self, abort_test=abort_test)
  File "c:\programdata\anaconda3\lib\site-packages\bumps\dream\core.py", line 306, in _run_dream
    assert pop.ctypes.data == np.ascontiguousarray(pop).ctypes.data
AssertionError

**Comment by pkienzle** [comment]
I do not understand why this is now an issue. The code for `_draw_pop` is pretty straightforward: return the current population, which is either returned from the loader on resume or from the last population, plus zero to force a copy.

If you can reproduce it, please confirm that the bad `_gen_current` is coming from a call to `_generation` and that the associated `_gen_current = x+0` is somehow not creating a contiguous copy.

**Comment by bmaranville** [comment]
Is this still an issue?  Does it need to be addressed before the imminent next release?

**Comment by acaruana2009** [comment]
I have not checked this recently, but from my perspective it is not imminent to be fixed before the next release.
